language: node_js

node_js:
 - node

# env:
#  global:
#    - CC_TEST_REPORTER_ID=be108253c82227c73b58af6d8c55eebd01042cc1e20bb7d87b785274c89f4afe

#before_script:
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build

script:
  - npx eslint .
  - npm test -- --coverage
  
#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 

#notifications:
#  email: false